AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Fn::Sub "${AWS::StackName}"

  '
Parameters:
  UserPoolNameCompany:
    Type: String
    Default: Fn::Sub "${AWS::StackName}"
Globals:
  Function:
    Runtime: python3.8
    CodeUri: ../src/
    Timeout: 180
    Layers:
    - Ref: CovcovLibsLayer
Resources:
  CovcovLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  CovcovLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Dependencies base layer for python apps
      ContentUri: s3://covcov/77fbe1b55b7bf2ef8a0b2f7c7df8e30b
      LayerName: covcov-libs
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8
  CovcovCompanyCognito:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Sub: ${UserPoolNameCompany}
      AliasAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      UsernameConfiguration:
        CaseSensitive: false
      MfaConfiguration: 'OFF'
      AccountRecoverySetting:
        RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
      Schema:
      - Name: email
        Required: true
        Mutable: true
      - Name: etablissement
        AttributeDataType: String
        Mutable: true
        Required: false
        StringAttributeConstraints:
          MaxLength: 30
          MinLength: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          RequireLowercase: true
          TemporaryPasswordValidityDays: 7
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubjectByLink: Votre lien de validation Covcov
        EmailMessageByLink: "Veuillez cliquer sur le lien ci-dessous pour v\xE9rifier\
          \ votre adresse e-mail. {##V\xE9rifier l'adresse e-mail##}"
      LambdaConfig:
        PreSignUp:
          Fn::GetAtt:
          - PreSignupFunction
          - Arn
        PostConfirmation:
          Fn::GetAtt:
          - PostConfirmationFunction
          - Arn
  CovcovClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: CovcovCompanyCognito
      ClientName: covcov-app
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      RefreshTokenValidity: 1
      AccessTokenValidity: 50
      IdTokenValidity: 60
  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_presignup.handle
      CodeUri: s3://covcov/a4e9b1d2c565a74a4dc7ea0cd9d0ca54
  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_postsignup_confirmation.handle
      CodeUri: s3://covcov/a4e9b1d2c565a74a4dc7ea0cd9d0ca54
Outputs:
  UserPoolId:
    Value:
      Ref: CovcovCompanyCognito
    Export:
      Name: UserPool::Id
    Description: CovcovCompanyCognito - Pool Id
  UserPoolArn:
    Value:
      Fn::GetAtt:
      - CovcovCompanyCognito
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-UserPoolArn
    Description: CovcovCompanyCognito - Pool Arn
  AppClientId:
    Value:
      Ref: CovcovClient
    Export:
      Name: UserPoolClient::Id
    Description: CovcovClient - Client Id
