Transform: AWS::Serverless-2016-10-31
Description: 'Stack: covcov-api-DEV

  '
Parameters:
  CognitoStackName:
    Type: String
    Default: covcov-cognito-DEV
Globals:
  Function:
    Runtime: python3.8
    CodeUri: ../src/
    Timeout: 180
    Layers:
    - Ref: CovcovLibsLayer
  Api:
    EndpointConfiguration:
      Type: REGIONAL
    GatewayResponses:
      UNAUTHORIZED:
        StatusCode: 401
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: '''*'''
    Cors:
      AllowMethods: '''POST, GET'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  CovcovLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  CovcovLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Dependencies base layer for python apps
      ContentUri: s3://covcov-dev/api/2c0d5223d8496c6b264b022f44183d2f
      LayerName: covcov-libs
      RetentionPolicy: Retain
      CompatibleRuntimes:
      - python3.8
    Metadata:
      BuildMethod: python3.8
  CovcovApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          CovcovCompanyAuthorizer:
            UserPoolArn:
              Fn::ImportValue:
                Fn::Sub: ${CognitoStackName}-UserPoolArn
            Identity:
              Header: auth-id-token
  CompanyDomainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_company_domain.handle
      Events:
        CovcovApi:
          Type: Api
          Properties:
            Path: /company_domain
            Method: post
            RestApiId:
              Ref: CovcovApi
            Auth:
              Authorizer: CovcovCompanyAuthorizer
      CodeUri: s3://covcov-dev/api/8e74b97e88b9b03ced58d3a73a5da4e1
  CompanyCasContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_cas_contact.handle
      Events:
        CovcovApi:
          Type: Api
          Properties:
            Path: /c_ccontact
            Method: post
            RestApiId:
              Ref: CovcovApi
            Auth:
              Authorizer: CovcovCompanyAuthorizer
      CodeUri: s3://covcov-dev/api/8e74b97e88b9b03ced58d3a73a5da4e1
  VisitDomainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_visit_domain.handle
      Events:
        CovcovApi:
          Type: Api
          Properties:
            Path: /visit_domain
            Method: post
            RestApiId:
              Ref: CovcovApi
      CodeUri: s3://covcov-dev/api/8e74b97e88b9b03ced58d3a73a5da4e1
  FakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_fake.handle
      CodeUri: s3://covcov-dev/api/7250e6882f9724bed256354789d08df0
Outputs:
  CovcovApi:
    Description: API Gateway endpoint URL for Prod stage for CovcovApi functions
    Value:
      Fn::Sub: https://${CovcovApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  CompanyDomainFunction:
    Description: Company Domain Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CompanyDomainFunction
      - Arn
  CompanyCasContactFunction:
    Description: Company CasContact Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CompanyCasContactFunction
      - Arn
  VisitDomainFunction:
    Description: Visit Domain Lambda Function ARN
    Value:
      Fn::GetAtt:
      - VisitDomainFunction
      - Arn
  CompanyDomainFunctionIamRole:
    Description: Implicit IAM Role created for CompanyDomainFunction
    Value:
      Fn::GetAtt:
      - CompanyDomainFunctionRole
      - Arn
  VisitDomainFunctionIamRole:
    Description: Implicit IAM Role created for CompanyDomainFunction
    Value:
      Fn::GetAtt:
      - VisitDomainFunctionRole
      - Arn
